version: '3'

services:

  backend_app_node:
    build: .
    container_name: backend_app_node
    ports:
      - "3000:3000"
    networks:
      app_node_net:

  frontend_app_node:
    image: nginx
    container_name: frontend_app_node
    volumes:
      - ./logs/nginx:/var/log/nginx
      - ./:/var/www:delegated
      # - ./reverse-proxy.conf:/etc/nginx/conf.d/reverse-proxy.conf
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    links:
      - backend_app_node
    networks:
      app_node_net:

networks:
  app_node_net:
    driver: bridge
